#!/bin/sh
# mihomo-openwrt installer / updater.
#
# Installs (or updates to) the latest mihomo + mihomo-metacubexd APKs from
# https://github.com/sers88/mihomo-openwrt/releases, creates a starter
# /etc/mihomo/config.yaml with a random secret if none exists, and enables
# and (re)starts the service. Re-running the script updates to the latest
# release; existing configs are never touched (they are apk conffiles).
#
# Usage:
#   sh install.sh              install/update, enable + restart service
#   sh install.sh --dnsmasq    also forward router DNS through mihomo
#   sh install.sh --no-service install/update packages only
#
# Runs on-device under BusyBox ash: POSIX sh only, no jq/bashisms.

set -eu

REPO="sers88/mihomo-openwrt"
API_URL="https://api.github.com/repos/${REPO}/releases/latest"
CONFIG_FILE="/etc/mihomo/config.yaml"

DNSMASQ=0
SERVICE=1
for arg in "$@"; do
    case "$arg" in
        --dnsmasq) DNSMASQ=1 ;;
        --no-service) SERVICE=0 ;;
        *)
            echo "Usage: sh install.sh [--dnsmasq] [--no-service]" >&2
            echo "Unknown option: $arg" >&2
            exit 1
            ;;
    esac
done

msg()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run this script as root"

# --- 1. Architecture -------------------------------------------------------
. /etc/openwrt_release 2>/dev/null || die "not an OpenWrt system (/etc/openwrt_release missing)"
ARCH="${DISTRIB_ARCH:-}"
case "$ARCH" in
    aarch64_generic|x86_64) ;;
    *) die "unsupported architecture '${ARCH}' (builds exist for aarch64_generic and x86_64)" ;;
esac
msg "architecture: $ARCH"

# --- 2. Download helper (curl preferred, uclient-fetch fallback) -----------
fetch() { # <url> <dest|'-'>
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL -o "$2" "$1"
    elif command -v uclient-fetch >/dev/null 2>&1; then
        uclient-fetch -q -O "$2" "$1"
    else
        msg "no downloader found, installing curl"
        apk add curl >/dev/null 2>&1 || die "cannot install curl"
        curl -fsSL -o "$2" "$1"
    fi
}

# --- 3. Resolve latest release assets --------------------------------------
msg "resolving latest release"
json=$(fetch "$API_URL" -) || die "failed to reach the GitHub API (rate limit? no connectivity?)"
# Only trust real asset download URLs; the release body (README copy) may
# mention *.apk files too and must not leak into the extraction below.
urls=$(printf '%s\n' "$json" | grep -o 'https://github\.com/[^"]*/releases/download/[^"]*\.apk' | sort -u)
# Core asset is mihomo-<version>-r1_<arch>.apk — the leading digit after
# "mihomo-" distinguishes it from mihomo-metacubexd-<version>-...
core_url=$(printf '%s\n' "$urls" | grep "/mihomo-[0-9][^/]*_${ARCH}\.apk$" | head -n 1)
ui_url=$(printf '%s\n' "$urls" | grep "/mihomo-metacubexd-[^/]*_${ARCH}\.apk$" | head -n 1)
[ -n "$core_url" ] || die "no mihomo APK for ${ARCH} in the latest release"
[ -n "$ui_url" ]   || die "no mihomo-metacubexd APK for ${ARCH} in the latest release"

# --- 4. Download and install ------------------------------------------------
tmp=$(mktemp -d /tmp/mihomo-install.XXXXXX) || die "mktemp failed"
trap 'rm -rf "$tmp"' EXIT

msg "downloading $(basename "$core_url")"
fetch "$core_url" "$tmp/mihomo.apk"
msg "downloading $(basename "$ui_url")"
fetch "$ui_url" "$tmp/ui.apk"

apk add --allow-untrusted "$tmp/mihomo.apk" || die "apk add mihomo failed"
apk add --allow-untrusted "$tmp/ui.apk"    || die "apk add mihomo-metacubexd failed"

[ "$SERVICE" -eq 1 ] || { msg "done (--no-service): packages installed, service untouched"; exit 0; }

# --- 5. Starter config (only if missing) -----------------------------------
created_config=0
if [ ! -f "$CONFIG_FILE" ]; then
    secret=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')
    mkdir -p /etc/mihomo
    cat > "$CONFIG_FILE" <<EOF
# Starter config generated by install.sh — replace the placeholder proxy
# with your own server(s) or a subscription:
#   https://wiki.metacubex.one/en/config/proxies/
#   https://wiki.metacubex.one/en/config/proxy-providers/
# Full annotated example: /etc/mihomo/example.yaml

external-controller: 0.0.0.0:9090
secret: "${secret}"
external-ui: ui

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - 1.1.1.1

proxies:
  - name: "my-proxy"
    type: ss
    server: 203.0.113.1
    port: 8388
    cipher: aes-256-gcm
    password: "secret"

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - my-proxy
      - DIRECT

rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
EOF
    chmod 600 "$CONFIG_FILE"
    created_config=1
    msg "created starter config $CONFIG_FILE"
else
    msg "existing $CONFIG_FILE kept as-is"
fi

# --- 6. Enable and (re)start the service ------------------------------------
uci -q get mihomo.main >/dev/null || uci set mihomo.main=mihomo
uci set mihomo.main.enabled='1'
uci commit mihomo
/etc/init.d/mihomo enable
/etc/init.d/mihomo restart

# --- 7. Optional: router DNS through mihomo ----------------------------------
if [ "$DNSMASQ" -eq 1 ]; then
    msg "forwarding dnsmasq to mihomo DNS (127.0.0.1#1053)"
    uci -q delete dhcp.@dnsmasq[0].server || true
    uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#1053'
    uci set dhcp.@dnsmasq[0].noresolv='1'
    uci commit dhcp
    /etc/init.d/dnsmasq restart
fi

# --- 8. Summary ----------------------------------------------------------------
lan_ip=$(uci -q get network.lan.ipaddr || echo "192.168.1.1")
echo
msg "installed: $(mihomo -v 2>/dev/null | head -n 1)"
msg "service:   /etc/init.d/mihomo (enabled, restarted)"
if [ "$created_config" -eq 1 ]; then
    msg "dashboard: http://${lan_ip}:9090/ui  (secret: ${secret})"
    msg "NOTE: edit ${CONFIG_FILE} and replace the placeholder proxy, then run: /etc/init.d/mihomo restart"
else
    msg "dashboard: http://${lan_ip}:9090/ui  (secret: see ${CONFIG_FILE})"
fi
msg "logs:      logread -e mihomo"
